### Send a form with the text and file fields
POST http://localhost:8086/rest/v1/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="chart-stock-performance.png"
Content-Type: image/png

< ./chart-stock-performance.png
--WebAppBoundary--

###

### Send a form with the text and file fields
POST http://localhost:8086/rest/v1/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="MCP-server.pdf"
Content-Type: application/pdf

< ./MCP-server.pdf
--WebAppBoundary--

###
### microservices-on-aws.pdf
POST http://localhost:8086/rest/v1/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="microservices-on-aws.pdf"
Content-Type: application/pdf

< ./microservices-on-aws.pdf
--WebAppBoundary--

###
POST http://localhost:8086/restv1/v1/load-url
Content-Type: application/json

{
  "url": "https://www.microsoft.com/investor/reports/ar24/index.html"
}
###
