import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.wk'
version = '0.0.1-SNAPSHOT'
description = 'ti-document-worker'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springAiVersion', "2.0.1")
    apacheCommonsLang3Version = '3.18.0'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

dependencies {
    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.amqp:spring-rabbit-stream'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'

    // Spring AI
    implementation 'org.springframework.boot:spring-boot-starter-restclient'
    //implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory'
    implementation 'org.springframework.ai:spring-ai-client-chat'
    implementation 'org.springframework.ai:spring-ai-openai'
    implementation 'com.openai:openai-java-client-okhttp:4.49.0'
    implementation 'org.springframework.ai:spring-ai-mistral-ai'
    implementation 'org.springframework.ai:spring-ai-pgvector-store'
    implementation 'org.springframework.ai:spring-ai-rag'
    implementation 'org.springframework.ai:spring-ai-tika-document-reader'
    implementation 'org.springframework.ai:spring-ai-pdf-document-reader'
    implementation 'org.springframework.ai:spring-ai-markdown-document-reader'
    implementation 'org.springframework.ai:spring-ai-jsoup-document-reader'

    // Database
    runtimeOnly 'org.postgresql:postgresql'

    // OpenAPI & DevTools
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Observability & Metrics
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    runtimeOnly 'io.micrometer:micrometer-tracing-bridge-otel'
    runtimeOnly 'io.opentelemetry:opentelemetry-exporter-zipkin'

    // Annotation Processor
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Utility Libraries
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'commons-fileupload:commons-fileupload:1.4'
    implementation "org.apache.commons:commons-lang3:${apacheCommonsLang3Version}"
    implementation 'org.apache.httpcomponents.client5:httpclient5'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-amqp-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.processResources {
    filesMatching('application.yaml') {
        filter(ReplaceTokens, tokens: [
                'project.version': project.version.toString()
        ])
    }
}

tasks.named('jar') {
    enabled = false
}