import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.14'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.wk'
version = '0.0.1-SNAPSHOT'
description = 'ti-document-worker'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

ext {
    springAiVersion = '1.1.5'
    apacheCommonsLang3Version = '3.18.0'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

dependencies {

    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.amqp:spring-rabbit-stream'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // Spring Data JDBC
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'

    // Spring AI
    implementation 'org.springframework.ai:spring-ai-openai'
    implementation 'org.springframework.ai:spring-ai-advisors-vector-store'
    implementation 'org.springframework.ai:spring-ai-pdf-document-reader'
    implementation 'org.springframework.ai:spring-ai-tika-document-reader'
    implementation 'org.springframework.ai:spring-ai-rag'
    implementation 'org.springframework.ai:spring-ai-mistral-ai'
    implementation 'org.springframework.ai:spring-ai-pgvector-store'
    implementation 'org.springframework.ai:spring-ai-markdown-document-reader'

    implementation 'org.jsoup:jsoup:1.17.2'
//commons-fileupload
    implementation 'commons-fileupload:commons-fileupload:1.4'

    // Security
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // Swagger / OpenAPI
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.16'

    // PostgreSQL
    runtimeOnly 'org.postgresql:postgresql'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Observability dependencies
    // Actuator
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    // Metrics
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    // Micrometer Tracing -> OpenTelemetry
    runtimeOnly 'io.micrometer:micrometer-tracing-bridge-otel'
    // OpenTelemetry -> Zipkin exporter
    runtimeOnly 'io.opentelemetry:opentelemetry-exporter-zipkin'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Apache Commons
    implementation "org.apache.commons:commons-lang3:${apacheCommonsLang3Version}"

    // Apache HttpClient 5
    implementation 'org.apache.httpcomponents.client5:httpclient5'

    // Tests
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'

    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
}


tasks.named('test') {
    useJUnitPlatform()
}

tasks.processResources {
    filesMatching('application.yaml') {
        filter(ReplaceTokens, tokens: [
                'project.version': project.version.toString()
        ])
    }
}

tasks.named('jar') {
    enabled = false
}
