package com.wk.ti.document.model;

public final class DocumentMetadataKeys {

    private DocumentMetadataKeys() {
    }

    // Metadata generated by PagePdfDocumentReader
    public static final String PAGE_NUMBER = "page_number";
    public static final String FILE_NAME = "file_name";

    // Application-specific metadata
    public static final String DOCUMENT_ID = "document_id";
    public static final String SECTION_ID = "section_id";
    public static final String SECTION_NUMBER = "section_number";

    // Metadata used by your application/API
    public static final String FILENAME = "filename";
}